image: gitlab.ri.domain:4567/devops/ati-runner

stages:
  - build images

.rnd_tags:
  tags:
   - alpine
   - docker
   - rnd

.docker_login_tpl: &docker_login
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.job_template: &build_images
  <<: *docker_login
  stage: build images
  cache: {}
  extends: .rnd_tags
  script:
    - >
      docker build --cache-from $CI_REGISTRY_IMAGE/arq_dashboard:cache-latest
      -t $CI_REGISTRY_IMAGE/arq_dashboard:$CI_COMMIT_REF_SLUG
      -f dashboard.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/arq_dashboard:$CI_COMMIT_REF_SLUG

build_image:
  <<: *build_images
