image: gitlab.ri.domain:4567/devops/ati-runner

stages:
  - build images

.rnd_tags:
  tags:
   - alpine
   - docker
   - rnd

.check-branch-behind-master: &check-branch-behind-master
- >
  if [ $(git log HEAD..origin/master --pretty=oneline | wc -l) -gt 0 ];
  then echo "Ветка отстала от мастера!";
  exit 1;
  fi

.docker_login_tpl: &docker_login
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.job_template: &build_images
  <<: *docker_login
  stage: build images
  cache: {}
  extends: .rnd_tags
  script:
    - *check-branch-behind-master
    - docker pull $CI_REGISTRY_IMAGE/arq_dashboard:cache-latest || true
    - >
      docker build --cache-from $CI_REGISTRY_IMAGE/arq_dashboard:cache-latest
      -t $CI_REGISTRY_IMAGE/arq_dashboard:$CI_COMMIT_REF_SLUG
      -t $CI_REGISTRY_IMAGE/arq_dashboard:cache-latest
      -f $BUILD_IMAGE.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/arq_dashboard:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE/arq_dashboard:cache-latest

build_image:
  <<: *build_images
